// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vyukovy_pavouk.DBContexts;

#nullable disable

namespace vyukovypavouk.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20221022090056_TestBV2")]
    partial class TestBV2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("vyukovy_pavouk.Data.Kapitola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdPredmetu")
                        .HasColumnType("int");

                    b.Property<string>("Kontent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Název")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Perex")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdPredmetu");

                    b.ToTable("Kapitoly");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Predmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Predmet");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Skupina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ID_Predmetu")
                        .HasColumnType("int");

                    b.Property<string>("TmSkupina")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ID_Predmetu");

                    b.ToTable("Skupina");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.SkupinaStudent", b =>
                {
                    b.Property<int>("SkupinaId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("SkupinaId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("SkupinaStudent");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Splneni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Id_kapitoly")
                        .HasColumnType("int");

                    b.Property<int>("Id_skupiny")
                        .HasColumnType("int");

                    b.Property<int>("Id_studenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_studenta");

                    b.ToTable("Splneni");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Jmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Videa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdKapitoly")
                        .HasColumnType("int");

                    b.Property<string>("Odkaz")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("IdKapitoly");

                    b.ToTable("Videa");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Zadani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdKapitoly")
                        .HasColumnType("int");

                    b.Property<string>("Odkaz")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("IdKapitoly");

                    b.ToTable("Zadani");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Kapitola", b =>
                {
                    b.HasOne("vyukovy_pavouk.Data.Predmet", "predmet")
                        .WithMany("Kapitoly")
                        .HasForeignKey("IdPredmetu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("predmet");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Skupina", b =>
                {
                    b.HasOne("vyukovy_pavouk.Data.Predmet", "predmet")
                        .WithMany("Skupiny")
                        .HasForeignKey("ID_Predmetu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("predmet");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.SkupinaStudent", b =>
                {
                    b.HasOne("vyukovy_pavouk.Data.Skupina", "Skupina")
                        .WithMany("Student")
                        .HasForeignKey("SkupinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vyukovy_pavouk.Data.Student", "Student")
                        .WithMany("SkupinaStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skupina");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Splneni", b =>
                {
                    b.HasOne("vyukovy_pavouk.Data.Student", "student")
                        .WithMany("Splneni")
                        .HasForeignKey("Id_studenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("student");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Videa", b =>
                {
                    b.HasOne("vyukovy_pavouk.Data.Kapitola", "kapitola")
                        .WithMany("Videa")
                        .HasForeignKey("IdKapitoly")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kapitola");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Zadani", b =>
                {
                    b.HasOne("vyukovy_pavouk.Data.Kapitola", "kapitola")
                        .WithMany("Zadani")
                        .HasForeignKey("IdKapitoly")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kapitola");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Kapitola", b =>
                {
                    b.Navigation("Videa");

                    b.Navigation("Zadani");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Predmet", b =>
                {
                    b.Navigation("Kapitoly");

                    b.Navigation("Skupiny");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Skupina", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("vyukovy_pavouk.Data.Student", b =>
                {
                    b.Navigation("SkupinaStudent");

                    b.Navigation("Splneni");
                });
#pragma warning restore 612, 618
        }
    }
}
